version: '3.1'

secrets:
  JWT_SECRETS:
    file: ./src/jwt_secrets_demo.json

services:
  timers-backend:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo-db
    secrets:
      - JWT_SECRETS
    environment:
      JWT_SECRET_FILE_NAME: jwt_secrets_demo.json
      MONGO_DATABASE_NAME: timers
      MONGO_DATABASE_SERVER: mongo-db
      FLASK_DEFAULT_PORT: 8080
      FLASK_IS_DEBUG: 'True'
      FLASK_USE_RELOADER: ''
      MONGO_DATABASE_PORT: 27017
      IS_DOCKER_ENV: 'True'
  mongo-db:
    image: mongo     
