version: '3.1'

secrets:
  JWT_SECRETS:
    file: ./src/jwt_secrets.json

services:
  timers-backend:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo-db
    secrets:
      - JWT_SECRETS
    environment:
      JWT_SECRET_FILE_NAME: jwt_secrets.json
      MONGO_DATABASE_NAME: timers
      MONGO_DATABASE_SERVER: mongo-db
      FLASK_DEFAULT_PORT: 8080
      FLASK_IS_DEBUG: 'False'
      FLASK_USE_RELOADER: 'False'

      IS_DOCKER_ENV: 'True'
  mongo-db:
    image: mongo
    volumes:
      - '/var/lib/boot2docker/my-mongodb-data/:/data/db'