version: '3.1'

secrets:
  JWT_SECRETS:
    file: ./configuration/jwt_secrets.json

services:
  timers-backend:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo-db
    secrets:
      - JWT_SECRETS
    environment:
      JWT_SECRET_FILE_NAME: JWT_SECRETS
      MONGO_CONNECTION_STRING: mongodb://mongo-db:27017/
      MONGO_DATABASE_NAME: timers
      IS_DOCKER_ENV: true
  mongo-db:
    image: mongo
    volumes:
      - '/var/lib/boot2docker/my-mongodb-data/:/data/db'